<?php

namespace ContainerKCKjflM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllereliminarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZyeCPgn.App\Controller\BaseController::eliminar()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZyeCPgn.App\\Controller\\BaseController::eliminar()'] = ($container->privates['.service_locator.ZyeCPgn'] ?? $container->load('get_ServiceLocator_ZyeCPgnService'))->withContext('App\\Controller\\BaseController::eliminar()', $container);
    }
}
