<?php

namespace ContainerKCKjflM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllermostrarCategoriasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7ajBy2.App\Controller\BaseController::mostrar_categorias()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7ajBy2.App\\Controller\\BaseController::mostrar_categorias()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\BaseController::mostrar_categorias()', $container);
    }
}
