<?php

namespace ContainerKCKjflM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCestaCompraService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\CestaCompra' shared autowired service.
     *
     * @return \App\Services\CestaCompra
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Services/CestaCompra.php';

        return $container->privates['App\\Services\\CestaCompra'] = new \App\Services\CestaCompra(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
