<?php

namespace ContainerJJMcUec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YDTuSJuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yDTuSJu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yDTuSJu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BaseController::mostrar_categorias' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\BaseController::mostrar_categorias()', 'getBaseControllermostrarCategoriasService', true],
            'App\\Controller\\BaseController::mostrar_productos' => ['privates', '.service_locator.xeBNbb2.App\\Controller\\BaseController::mostrar_productos()', 'getBaseControllermostrarProductosService', true],
            'App\\Controller\\BaseController::anadir_productos' => ['privates', '.service_locator.6fJQKpk.App\\Controller\\BaseController::anadir_productos()', 'getBaseControlleranadirProductosService', true],
            'App\\Controller\\BaseController::cesta' => ['privates', '.service_locator.ZyeCPgn.App\\Controller\\BaseController::cesta()', 'getBaseControllercestaService', true],
            'App\\Controller\\BaseController::eliminar' => ['privates', '.service_locator.ZyeCPgn.App\\Controller\\BaseController::eliminar()', 'getBaseControllereliminarService', true],
            'App\\Controller\\BaseController::pedido' => ['privates', '.service_locator.UuJAUpE.App\\Controller\\BaseController::pedido()', 'getBaseControllerpedidoService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BaseController:mostrar_categorias' => ['privates', '.service_locator.E7ajBy2.App\\Controller\\BaseController::mostrar_categorias()', 'getBaseControllermostrarCategoriasService', true],
            'App\\Controller\\BaseController:mostrar_productos' => ['privates', '.service_locator.xeBNbb2.App\\Controller\\BaseController::mostrar_productos()', 'getBaseControllermostrarProductosService', true],
            'App\\Controller\\BaseController:anadir_productos' => ['privates', '.service_locator.6fJQKpk.App\\Controller\\BaseController::anadir_productos()', 'getBaseControlleranadirProductosService', true],
            'App\\Controller\\BaseController:cesta' => ['privates', '.service_locator.ZyeCPgn.App\\Controller\\BaseController::cesta()', 'getBaseControllercestaService', true],
            'App\\Controller\\BaseController:eliminar' => ['privates', '.service_locator.ZyeCPgn.App\\Controller\\BaseController::eliminar()', 'getBaseControllereliminarService', true],
            'App\\Controller\\BaseController:pedido' => ['privates', '.service_locator.UuJAUpE.App\\Controller\\BaseController::pedido()', 'getBaseControllerpedidoService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BaseController::mostrar_categorias' => '?',
            'App\\Controller\\BaseController::mostrar_productos' => '?',
            'App\\Controller\\BaseController::anadir_productos' => '?',
            'App\\Controller\\BaseController::cesta' => '?',
            'App\\Controller\\BaseController::eliminar' => '?',
            'App\\Controller\\BaseController::pedido' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BaseController:mostrar_categorias' => '?',
            'App\\Controller\\BaseController:mostrar_productos' => '?',
            'App\\Controller\\BaseController:anadir_productos' => '?',
            'App\\Controller\\BaseController:cesta' => '?',
            'App\\Controller\\BaseController:eliminar' => '?',
            'App\\Controller\\BaseController:pedido' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
