<?php

namespace ContainerJJMcUec;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControlleranadirProductosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6fJQKpk.App\Controller\BaseController::anadir_productos()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6fJQKpk.App\\Controller\\BaseController::anadir_productos()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine', 'getDoctrineService', false],
            'cesta' => ['privates', 'App\\Services\\CestaCompra', 'getCestaCompraService', true],
        ], [
            'em' => '?',
            'cesta' => 'App\\Services\\CestaCompra',
        ]))->withContext('App\\Controller\\BaseController::anadir_productos()', $container);
    }
}
