<?php

namespace ContainerV17xEGx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBaseControllermostrarProductosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xeBNbb2.App\Controller\BaseController::mostrar_productos()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xeBNbb2.App\\Controller\\BaseController::mostrar_productos()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'em' => '?',
        ]))->withContext('App\\Controller\\BaseController::mostrar_productos()', $container);
    }
}
