<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV17xEGx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV17xEGx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV17xEGx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV17xEGx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerV17xEGx\App_KernelDevDebugContainer([
    'container.build_hash' => 'V17xEGx',
    'container.build_id' => 'dddef67b',
    'container.build_time' => 1769542357,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV17xEGx');
