<?php

namespace Container4YwW79x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZyeCPgnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZyeCPgn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZyeCPgn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cesta' => ['privates', 'App\\Services\\CestaCompra', 'getCestaCompraService', true],
        ], [
            'cesta' => 'App\\Services\\CestaCompra',
        ]);
    }
}
